server:
  port: 10999
  servlet:
    context-path: /account_service

spring:
  name: account_service_01
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_ADDR:localhost:4000}/accountCenter?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:}
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      pool-prepared-statements: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-locations: mybatis-config.xml

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation: TRACE
    com:
      tank:
        dao: debug
